### ISSUE TITLE
Enhancement: Is it possible to add air filter status?

### ISSUE THREAD

**Issue by dbaron92** [bodyscape/cielo_home#12]
Everything is working perfectly with my Mrcool DIY unit but I noticed that air filter status feature is not exist. Im not sure if its good idea or/and hard to add the feature? The feature under eSaver category in Mrcool app.

**Comment by bodyscape** [comment]
I'll check on it!

**Comment by galoi9** [comment]
I'm having a issue where it will not turn on or off my system. From the app the controls work fine, but when I use HA, I get a beep but the power state never changes.

**Comment by bodyscape** [comment]
Can you share me the response json from this url 'https://api.smartcielo.com/web/devices?limit=420' on this Cielo website https://home.cielowigle.com/.

**Comment by galoi9** [comment]
I presume you mean to login to the website to be authenticated and then issue the api, if so, I get {"message":"Forbidden"}. if there is a different process, let me know.

**Comment by bodyscape** [comment]
![image](https://github.com/bodyscape/cielo_home/assets/30115568/e698ad1d-159f-48af-8667-481eb35081a3)

**Comment by galoi9** [comment]
I think this is what you want, its hard to see your picture.
<img width="1469" alt="image" src="https://github.com/bodyscape/cielo_home/assets/101365964/4aa158b6-ef35-44b2-822f-3be6586d5a6f">

**Comment by bodyscape** [comment]
well no ;) anyway try the version 1.5.1

**Comment by galoi9** [comment]
1.5.2 does work. 👍
