### ISSUE TITLE
Possible API Issue: Unable to control power from HA or Web

### ISSUE THREAD

**Issue by Z0y6h0kS9X** [bodyscape/cielo_home#13]
Recently I have run into an issue where HA can no longer control specifically the power functions (On/Off) of the HVAC mini-split using this integration.  Looking into the issue I have found the following to be true.

1. Only the power functions (off/on) are affected, I can change fan speed and function (Heat/Cool/etc) just fine.
2. Using Cielo's web application (https://home.cielowigle.com/) exhibits the same behavior.
3. Use of either the buttons on the cielo, or the android application both work as they should.

This leads me to believe that something about the web calls broke (as otherwise the web app should work) - and I am not adept with python, but it seems this is emulating the functionality of the web app application.  This would explain why both the web app and the HA integration broke at the same time, also why android and device actions work.  Is anyone else having this issue?  HA debug logs of a successful event and an unsuccessful event, as well as the environment are below.

## Environment: 
- Daikin Mini-Split AC.
- Cielo Breez PLUS (FW: 1.1.1.2.4.1)
- Home Assistant 2023.6.2
- cielo_home 1.4.6

## Success
2023 - 06 - 15 15: 46: 50.908 DEBUG(MainThread)[custom_components.cielo_home.cielohome]Receive Json: 
```json
{
    "message_type": "StateUpdate",
    "action": {
        "uirules": "default:default:default",
        "device_status": "off",
        "temp": "72",
        "action_source": "MAC_ADDRESS",
        "statustimestamp": "1686856365",
        "fanspeed": "high",
        "turbo": "off",
        "end_turbo_timestamp": "1686856053",
        "mode": "cool",
        "swing": "auto",
        "followme": "off",
        "ontimestamp": "1686858411",
        "start_turbo_timestamp": "1686856053",
        "power": "on",
        "mode_timestamp": "1686856053",
        "timestamp": "1686858411",
        "moderules": "default:default:default"
    },
    "mac_address": "C45BBE68149E",
    "mid": "5f837565312cc7e7",
    "stateSync": "0",
    "lat_env_var": {
        "temperature": "77",
        "humidity": "50"
    },
    "device_status": 1,
    "device_name": "AC_UNIT",
    "fw_version": "1.1.1,2.4.1",
    "accessToken": "-----",
    "refreshToken": "-----"
}
```

## Failure
2023 - 06 - 15 15: 46: 41.975 DEBUG(MainThread)[custom_components.cielo_home.cielohome]Receive Json: 
```json
{
    "message_type": "StateUpdate",
    "action": {
        "uirules": "default:default:default",
        "device_status": "off",
        "temp": "72",
        "action_source": "WEB/StateSync",
        "statustimestamp": "1686856365",
        "fanspeed": "high",
        "turbo": "off",
        "end_turbo_timestamp": "1686856053",
        "mode": "cool",
        "swing": "auto",
        "followme": "off",
        "ontimestamp": "1686858402",
        "start_turbo_timestamp": "1686856053",
        "power": "off",
        "mode_timestamp": "1686856053",
        "timestamp": "1686858402",
        "moderules": "default:default:default"
    },
    "mac_address": "MAC_ADDRESS",
    "mid": "WEB",
    "stateSync": "0",
    "lat_env_var": {
        "temperature": "77",
        "humidity": "50"
    },
    "device_status": 1,
    "device_name": "AC_UNIT",
    "fw_version": "1.1.1,2.4.1",
    "accessToken": "-----",
    "refreshToken": "-----"
}
```

**Comment by bodyscape** [comment]
Since when you have this behaviour?

**Comment by Z0y6h0kS9X** [comment]
Started about 1 week ago, it was on 1.4.5 and I updated to 1.4.6 when it was released - so it wasn't caused by that if that is what you are thinking.  Do you see the same behavior on your setup?

**Comment by bodyscape** [comment]
Nah, everything work fine on mine.. you have a weird one! I know Tuesday PM the Cielo servers was down. Maybe they updated. But this integration is base on the website version. So if tour device don't work on the website, i don't know if i can do something.

**Comment by Z0y6h0kS9X** [comment]
okay, will have to assume that it is related to my HW - closing the issue if it can't be reproduced, but I'll let you know if I figure anything out.

**Comment by bodyscape** [comment]
If you can maybe send me the websocket data in the debug windows of Chrome browser in the website version. Maybe we will find something.

**Comment by Z0y6h0kS9X** [comment]
Attached is the har exported from chrome with the websocket information, looks like some relevant information starts on 18687...

"_resourceType": "websocket",
        "_webSocketMessages": [
          {
            "type": "send",
            "time": 1686872835.248941,
            "opcode": 1,
            "data": "{\"action\":\"actionControl\",\"macAddress\":\"C45BBE68149E\",\"deviceTypeVersion\":\"BP01\",\"fwVersion\":\"1.1.1,2.4.1\",\"actionSource\":\"WEB\",\"applianceType\":\"AC\",\"applianceId\":2040,\"actionType\":\"power\",\"actionValue\":\"on\",\"connection_source\":1,\"token\":\"eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..O7y2HequVWbgkzXU7Lf4sA.juxnriL1M1PO2i9ZACjX4O6S1I-tuL0ewO56LhxnJeFplKDtGknSki9Yec2sUOpk60Vq70Zr_PbkdTKTv9n4Nxg1Yy1swDlci67upfTF7gVkiDKrWLM_JxUrlnjbkqTByg71_azEr-Xwi2hQbvMFEzoqJL-0qFC1rbLSrMlkP-mWTORXBLSIB-8KdaElOrZOSpm3h1LLqEl8VrJ6_lRZ8OjRCU6kLQ7RoXS2XBvwK07atR2Ce-f9epjLG3gdb4SN9ps8i4oIw-xpcGQPz7bC29MdvsbYU4n2PyUKJzVn5XyWVeHdws2qFsZ1Hy2voe8VpO8Ep0Aud_V8I_daRdm3vkxhK6j9hvWARW7m56fpx67V1KUQ-F9hzpdtqp28B9EY7pHPnurx9leVSqPd1tAIFqXRowyUKYTArXepwVEEqdX7IxBEzC2boa9NVWxwVnDlvEXQbA.3pMPMh3N0xHrcYlIPl_47Q\",\"actions\":{\"power\":\"on\",\"mode\":\"cool\",\"fanspeed\":\"auto\",\"temp\":\"72\",\"swing\":\"auto\",\"turbo\":\"off\",\"light\":\"off\",\"oldPower\":\"on\"},\"mid\":\"chrome-1686872612\",\"application_version\":\"1.0.0\",\"ts\":1686872834}"
          },
          {
            "type": "receive",
            "time": 1686872836.985973,
            "opcode": 1,
            "data": "{\"message_type\": \"StateUpdate\", \"action\": {\"uirules\": \"default:default:default\", \"device_status\": \"off\", \"temp\": \"72\", \"action_source\": \"WEB\", \"statustimestamp\": \"1686856365\", \"fanspeed\": \"auto\", \"turbo\": \"off\", \"end_turbo_timestamp\": \"1686856053\", \"mode\": \"cool\", \"swing\": \"auto\", \"followme\": \"off\", \"ontimestamp\": \"1686872838\", \"start_turbo_timestamp\": \"1686856053\", \"power\": \"on\", \"mode_timestamp\": \"1686864204\", \"timestamp\": \"1686872838\", \"moderules\": \"default:default:default\"}, \"mac_address\": \"C45BBE68149E\", \"mid\": \"WEB\", \"stateSync\": \"0\", \"lat_env_var\": {\"temperature\": \"73\", \"humidity\": \"48\"}, \"device_status\": 1, \"device_name\": \"Batcave\", \"fw_version\": \"1.1.1,2.4.1\"}"
          },
          {
            "type": "send",
            "time": 1686872840.2768698,
            "opcode": 1,
            "data": "{\"action\":\"actionControl\",\"macAddress\":\"C45BBE68149E\",\"deviceTypeVersion\":\"BP01\",\"fwVersion\":\"1.1.1,2.4.1\",\"actionSource\":\"WEB\",\"applianceType\":\"AC\",\"applianceId\":2040,\"actionType\":\"power\",\"actionValue\":\"off\",\"connection_source\":1,\"token\":\"eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..O7y2HequVWbgkzXU7Lf4sA.juxnriL1M1PO2i9ZACjX4O6S1I-tuL0ewO56LhxnJeFplKDtGknSki9Yec2sUOpk60Vq70Zr_PbkdTKTv9n4Nxg1Yy1swDlci67upfTF7gVkiDKrWLM_JxUrlnjbkqTByg71_azEr-Xwi2hQbvMFEzoqJL-0qFC1rbLSrMlkP-mWTORXBLSIB-8KdaElOrZOSpm3h1LLqEl8VrJ6_lRZ8OjRCU6kLQ7RoXS2XBvwK07atR2Ce-f9epjLG3gdb4SN9ps8i4oIw-xpcGQPz7bC29MdvsbYU4n2PyUKJzVn5XyWVeHdws2qFsZ1Hy2voe8VpO8Ep0Aud_V8I_daRdm3vkxhK6j9hvWARW7m56fpx67V1KUQ-F9hzpdtqp28B9EY7pHPnurx9leVSqPd1tAIFqXRowyUKYTArXepwVEEqdX7IxBEzC2boa9NVWxwVnDlvEXQbA.3pMPMh3N0xHrcYlIPl_47Q\",\"actions\":{\"power\":\"off\",\"mode\":\"cool\",\"fanspeed\":\"high\",\"temp\":\"72\",\"swing\":\"auto\",\"turbo\":\"off\",\"light\":\"off\",\"oldPower\":\"off\"},\"mid\":\"chrome-1686872612\",\"application_version\":\"1.0.0\",\"ts\":1686872839}"
          },
          {
            "type": "receive",
            "time": 1686872841.979055,
            "opcode": 1,
            "data": "{\"message_type\": \"StateUpdate\", \"action\": {\"uirules\": \"default:default:default\", \"device_status\": \"off\", \"temp\": \"72\", \"action_source\": \"WEB\", \"statustimestamp\": \"1686856365\", \"fanspeed\": \"auto\", \"turbo\": \"off\", \"end_turbo_timestamp\": \"1686856053\", \"mode\": \"cool\", \"swing\": \"auto\", \"followme\": \"off\", \"ontimestamp\": \"1686872843\", \"start_turbo_timestamp\": \"1686856053\", \"power\": \"off\", \"mode_timestamp\": \"1686864204\", \"timestamp\": \"1686872843\", \"moderules\": \"default:default:default\"}, \"mac_address\": \"C45BBE68149E\", \"mid\": \"WEB\", \"stateSync\": \"0\", \"lat_env_var\": {\"temperature\": \"73\", \"humidity\": \"48\"}, \"device_status\": 1, \"device_name\": \"Batcave\", \"fw_version\": \"1.1.1,2.4.1\"}"
          }
        ],

[home.cielowigle.com.har.txt](https://github.com/bodyscape/cielo_home/files/11764044/home.cielowigle.com.har.txt)

**Comment by bodyscape** [comment]
It's weird because both callback message 'StateUpdate' confirm your action is working. The first power on and the second power off.

**Comment by Z0y6h0kS9X** [comment]
Circling back to this after working with Cielo support - evidently some changes that they made to the API broke some things, my issue included.  They made some changes to the API after 'extensive testing' - not sure what that entailed - but it works now.  In case other people report similar issues.
