### ISSUE TITLE
Mr Cool multiple usb wifi adapters in cielo only first unit shows as a climate entity

### ISSUE THREAD

**Issue by yodashut** [bodyscape/cielo_home#17]
I have 10 different indoor Mr Cool Air handlers with the usb wifi dongle.  I can control them all in the Mr. Cool app.  When I added my cielo account to Home assistant, most of the units came in with controls for Freezing Point, and Power as switches and Target temperature as a variable entity; Status and Temperature as a sensor.

Only the first (alphabetically) unit came in including a climate entity with full control over operation, status, target temperature, preset, fan mode, and swing mode.

How can I get the other units to come in with climate entities?

I have attached a pdf showing how the devices present with and without the climate entities.

[cielo.pdf](https://github.com/bodyscape/cielo_home/files/12111900/cielo.pdf)

**Comment by bodyscape** [comment]
Do you have any error log on HA?

**Comment by yodashut** [comment]
I deleted the integration, restarted and added again.  Same result.  Attached are my logs from this morning.

[home-assistant.log.1.txt](https://github.com/bodyscape/cielo_home/files/12129931/home-assistant.log.1.txt)
[home-assistant.log.fault.txt](https://github.com/bodyscape/cielo_home/files/12129932/home-assistant.log.fault.txt)
[home-assistant.log.txt](https://github.com/bodyscape/cielo_home/files/12129933/home-assistant.log.txt)

**Comment by bodyscape** [comment]
try version 1.4.8

**Comment by yodashut** [comment]
That fixed it!!

BTW, as a note on my units, the swing settings result as follows
Auto and 1 seems to swing up and down on cool
2 and 3 freeze the vent at the location it is in.
