### ISSUE TITLE
Integration stopped working after adding Thermostat to CIelo

### ISSUE THREAD

**Issue by PinataPost** [bodyscape/cielo_home#18]
I just added Cielo's standard HVAC thermostat (the on with the C wire).  Afterwards, the integration stopped working alltogether.  When I check the log I see this 
`2023-07-31 12:55:52.153 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Cielo Home for cielo_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/cielo_home/__init__.py", line 48, in async_setup_entry
    list_devices = await api.async_get_devices()
  File "/config/custom_components/cielo_home/cielohome.py", line 334, in async_get_devices
    appliance_id: str = str(device["applianceId"])
KeyError: 'applianceId'`

**Comment by bodyscape** [comment]
which model of Cielo Thermostat you have?

**Comment by bodyscape** [comment]
if you let me connect to it, i can check it!

**Comment by PinataPost** [comment]
Hi @bodyscape I didn't see your reply until the captcha stuff started happening and I didn't want to bug you.  Now that it's all fixed, I'd love to tackle this issue!  What do you need from me to allow you to connect to it?

**Comment by PinataPost** [comment]
And I just tested with the latest update, it still "Fails to setup".

**Comment by bodyscape** [comment]
@PinataPost you can shoot me your login and password to bodyscape@protonmail.com.

**Comment by PinataPost** [comment]
Sent.

**Comment by bodyscape** [comment]
@PinataPost  well, can you try to login here : https://home.cielowigle.com/ ?? I can't finish the recaptcha always failed.

**Comment by bodyscape** [comment]
@PinataPost  Clearly in the Studio 02, i don't support the new Cielo Thermostat. The data receive is really different from the other Cielo devices. Maybe i can just skip this device for now, at least it won't crash and you will able to manage the other one.

**Comment by PinataPost** [comment]
Ah, bummer, well thanks for looking!  Yea a filter so at least one device is working would be great.

**Comment by bodyscape** [comment]
@PinataPost  try the version 1.6.3
