### ISSUE TITLE
"Websocket error, try reconnecting" on device changes

### ISSUE THREAD

**Issue by Goose1451** [bodyscape/cielo_home#2]
1.3.1 seems to be working, Thank you!  But I still get errors in the logs.  Some actions seem to fail, but I can't consistently reproduce.  Below is all that was provided by HASS.

This error originated from a custom integration.

Logger: custom_components.cielo_home.cielohome
Source: custom_components/cielo_home/cielohome.py:237
Integration: Cielo Home (documentation, issues)
First occurred: 7:15:06 AM (5 occurrences)
Last logged: 7:37:14 AM

Websocket error, try reconnecting

**Comment by bodyscape** [comment]
well that's a weird one! Who is your DNS provider?

**Comment by Goose1451** [comment]
Ziply fiber is my DNS provider.  I also run pihole, but I did not see any blocked traffic from home assistant client.  I tried disabling pihole and still seeing the error.  Even though there are times that the action takes successfully, I'm still seeing the error in the logs.

**Comment by bodyscape** [comment]
Can you try google or cloudflare DNS without your pihole? I run AdGuardHome with Cloudflare nerver have this error. The first part of the error stack appear to be a fail of a dns query. Also do you have a DNS loadbalancer?

**Comment by bodyscape** [comment]
@Goose1451 i made a new version 1.3.2 with better management of the websocket connection. You can try it, but i don't it's gonna solve your problem. But who knows! ;)

**Comment by Goose1451** [comment]
I just saw the update and tried it.  Really appreciate the help @bodyscape.  I am still getting errors in the same place but now a warning is included with the error on each action.

This error originated from a custom integration.

Logger: custom_components.cielo_home.cielohome
Source: custom_components/cielo_home/cielohome.py:232
Integration: Cielo Home (documentation, issues)
First occurred: 8:21:53 AM (2 occurrences)
Last logged: 8:23:41 AM

'light'

-------------------------------------------------------------

This error originated from a custom integration.

Logger: custom_components.cielo_home.cielohome
Source: custom_components/cielo_home/cielohome.py:240
Integration: Cielo Home (documentation, issues)
First occurred: 8:21:53 AM (2 occurrences)
Last logged: 8:23:41 AM

Try reconnection in 5 secondes

**Comment by bodyscape** [comment]
@Goose1451 did you try the 1.3.1 or 1.3.2?

**Comment by Goose1451** [comment]
@bodyscape, 1.3.2.  I've changed my dns to googles, and removed pihole from the equation.  I am not running a dns lb.

**Comment by bodyscape** [comment]
@Goose1451 can you share me the response json from this url 'https://api.smartcielo.com/web/devices?limit=420' on this Cielo website https://home.cielowigle.com/.

![image](https://user-images.githubusercontent.com/30115568/219489517-189e1d6d-1768-445f-a03a-3550a3b5ab6b.png)

**Comment by Goose1451** [comment]
@bodyscape , here's the response from the GET operation...  Sorry the formatting isn't sticking...

`{"status": 200, "message": "SUCCESS", "data": {"iosVersion": "4.1.6", "iosLatestVersion": "4.1.6", "iosExpiryTime": 1640977200, "androidVersion": "5.2.4", "androidLatestVersion": "5.2.4", "androidExpiryTime": 1640977200, "manufactureDBversion": "1008.01", "comfyMinimumLimit": {"fahRoomTemp": 0, "celRoomTemp": 0, "roomHumidity": 3}, "listDevices": [{"isLocalDbAck": 1, "deviceId": "wif2c2", "isFaren": 1, "macAddress": "24A1602B2465", "deviceName": "Cottage", "fwVersion": "1.0.9,2.4.0", "connectionSource": 0, "deviceType": "BREEZ-PLUS", "deviceTypeVersion": "BP01", "suggestedRemotes": [{"applianceId": "1716", "protocolId": 162, "isFaren": 1, "priority": 1}, {"applianceId": "1965", "protocolId": 235, "isFaren": 1, "priority": 6}, {"applianceId": "2551", "protocolId": 600, "isFaren": 0, "priority": 6}], "broadcastName": "Cielo_BP01_2B2465", "deviceTimeZone": "-07:00", "deviceTimeZoneName": "America/Los_Angeles", "applianceId": 1716, "applianceType": "AC", "isEnergyDevice": 0, "createdAt": 1662236999, "retainCreatedAt": 1662236999, "deviceStatus": 1, "latestAction": {"uirules": "default:default:default", "deviceStatus": "on", "temp": "68", "actionSource": "DeviceAction", "statustimestamp": "1676248744", "fanspeed": "auto", "turbo": "off", "endTurboTimestamp": "1616977069", "mode": "heat", "swing": "auto", "followme": "off", "ontimestamp": "1676478277", "startTurboTimestamp": "1616977069", "power": "on", "modeTimestamp": "1664916520", "timestamp": "1676579115", "moderules": "default:default:default"}, "wifiName": "Thomas%20Online", "userId": "hl73UxQVBV", "applianceSubtype": 1, "isOnceSyncedState": 1, "isFotaRequired": 1, "isUpdatingFw": 0, "fwInitiatedAt": 0, "fpFailureAttempts": 0, "fpSuccessAttempts": 0, "turboFailureAttempts": 0, "turboSuccessAttempts": 0, "scheduleDetails": {}, "isBlocked": 0, "blockMessage": "Unblocked", "groupId": "-1", "deviceSettings": {"screenDisplayValue": 1, "tbenabled": "1", "brightnessValue": "05"}, "latestBucketError": "0", "thermostatDeviceId": "N/A", "structureId": "N/A", "thermostatHomeAway": {}, "isBacktrackEnabled": 1, "latEnv": {"temp": 66.0, "humidity": 36.0}, "humCalibrationOffset": "0", "tempCalibrationOffset": "-3", "isHumCalibrationSync": 1, "isTempCalibrationSync": 1, "myRules": [], "myRuleConfiguration": {}, "deviceFilterDuration": "2689", "deviceFilterFlag": 1, "filterTimestamp": 1676533980, "deviceFilterDurationValue": 161340, "isWifiDisabled": 0, "priority": 1}], "listGroups": [], "devicesCount": 1}}`

**Comment by bodyscape** [comment]
@Goose1451 I think i find the problem, try the 1.3.3! ;)

**Comment by Goose1451** [comment]
@bodyscape, I think we have a winner!  Thank you!  I'll keep playing 1.3.3.  It's great to finally have my IR mini-split controlled by HA.

**Comment by bodyscape** [comment]
@Goose1451 my pleasure! :)
