### ISSUE TITLE
Mode select no longer working

### ISSUE THREAD

**Issue by skywurz** [bodyscape/cielo_home#25]
Whenever I try to turn on or off the system or change modes from HA it throws this error
```
This error originated from a custom integration.

Logger: custom_components.cielo_home.cielohome
Source: custom_components/cielo_home/cielohome.py:250
Integration: Cielo Home (documentation, issues)
First occurred: September 8, 2023 at 1:43:56 PM (8 occurrences)
Last logged: 9:49:59 AM

'message_type'
```
When I turn the system on from the official app or make changes manually at the unit HA updates and displays appropriately.

I'm running 1.5.3
Home Assistant 2023.9.0
Supervisor 2023.08.3
Operating System 10.5
Frontend 20230906.1 - latest 9

**Comment by bodyscape** [comment]
this integration don't work anymore! you can follow update here : https://github.com/bodyscape/cielo_home/issues/24
