### ISSUE TITLE
Manual Installation Missing Setup

### ISSUE THREAD

**Issue by jonathanbmorley** [bodyscape/cielo_home#28]
Hi there --

Love your work. I re-installed Cielo Home with a manual installation but am missing the configuration section for authentication tokens, etc. 

Any ideas?

![image](https://github.com/bodyscape/cielo_home/assets/19273738/336032c6-5f7d-4658-bb6c-34aa376fac4c)

**Comment by bodyscape** [comment]
You need to restart HA after the uninstall and after the install.

**Comment by jonathanbmorley** [comment]
I'm like, really good at _reading_. Thanks for the assist.

**Comment by bodyscape** [comment]
> I'm like, really good at _reading_. Thanks for the assist.

So this works, your ok?

**Comment by jonathanbmorley** [comment]
Yes, @bodyscape -- thank you for the quick assist!
