### ISSUE TITLE
Access Token Issue after HA Update

### ISSUE THREAD

**Issue by johnpernock** [bodyscape/cielo_home#32]
After updating my HA install and updating any out of date integrations in HACS, I noticed my Mr. Cool is not available inside Home Assistant. I noticed this in the logs, but I'm not too good and deciphering what is going on with the integration. Any help would be appreciated.

```
Logger: homeassistant.config_entries
Source: custom_components/cielo_home/__init__.py:39
Integration: Cielo Home (documentation, issues)
First occurred: 1:33:12 PM (5 occurrences)
Last logged: 1:48:24 PM

Error setting up entry Cielo Home for cielo_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/cielo_home/__init__.py", line 39, in async_setup_entry
    entry.data["access_token"],
    ~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'access_token'

```

**Comment by bodyscape** [comment]
Did you do that : If you have installed a version prior 1.6.0 you need to uninstall the integration and install it again. You need to restart HA after the uninstall and after the install.
