### ISSUE TITLE
Invalid authentication when trying to add to home assist

### ISSUE THREAD

**Issue by ablacklama** [bodyscape/cielo_home#33]
I had this integration previously working but since i added a new device and it wasn't detecting it, I tried deleting the integration and starting over. But now I can't get past the first step of adding the integration. I know my username/pass are correct since they work on the website. Is this a bug or am I doing something wrong? 

I should note that to try to fix this, i did try updating home assist core, and restart home assist.

![image](https://github.com/bodyscape/cielo_home/assets/22246943/97578ffa-48a5-4963-8042-a18bd40e03ee)

**Comment by bodyscape** [comment]
Please read the update procedure... you must  uninstall it, restart HA and install the last version.

**Comment by ablacklama** [comment]
ah, i thought i did uninstall it when i deleted the integration. But after deleting the files in `custom_components/cielo_home` and redownloading it in the HACS page, i was able to get it working. 

Perhaps adding instruction for how to uninstall it to the readme would be useful for future people.
