### ISSUE TITLE
Breeze Lite Mode Not Working

### ISSUE THREAD

**Issue by jgennari** [bodyscape/cielo_home#36]
When my Breeze Lite device is turned on, the Cielo web UI shows it on:

<img width="581" alt="image" src="https://github.com/bodyscape/cielo_home/assets/1387649/9d642ef4-846b-4847-a0e6-107e6135bdad">

But HA shows it off:

<img width="622" alt="image" src="https://github.com/bodyscape/cielo_home/assets/1387649/b15d47ae-5e08-42d9-aff5-b5f5f6d97759">

Here is the API return the web UI is parsing:

```
{
    "status": 200,
    "message": "SUCCESS",
    "data": {
        "iosVersion": "4.4.0",
        "iosLatestVersion": "4.4.0",
        "iosExpiryTime": 1693508400,
        "androidVersion": "5.4.6",
        "androidLatestVersion": "5.5.4",
        "androidExpiryTime": 1640977200,
        "manufactureDBversion": "1009.28",
        "comfyMinimumLimit": {
            "fahRoomTemp": 0,
            "celRoomTemp": 0,
            "roomHumidity": 3
        },
        "listDevices": [
            {
                "isLocalDbAck": 0,
                "deviceId": "qcYk9g",
                "isFaren": 1,
                "macAddress": "redacted",
                "deviceName": "Garage",
                "fwVersion": "1.0.2,1.0.2",
                "connectionSource": 1,
                "deviceType": "BREEZ-LITE",
                "deviceTypeVersion": "BL02",
                "suggestedRemotes": [
                    {
                        "applianceId": "2120",
                        "protocolId": 402,
                        "isFaren": 1,
                        "priority": 6
                    },
                    {
                        "applianceId": "2710",
                        "protocolId": 770,
                        "isFaren": 1,
                        "priority": 6
                    }
                ],
                "broadcastName": "Cielo_BL02_F9B78C",
                "deviceTimeZone": "-04:00",
                "deviceTimeZoneName": "America/New_York",
                "applianceId": 2120,
                "applianceType": "AC",
                "isEnergyDevice": 0,
                "createdAt": 1698179297,
                "retainCreatedAt": 1698179297,
                "deviceStatus": 1,
                "latestAction": {
                    "uirules": "default:default:default:default",
                    "deviceStatus": "off",
                    "temp": "78",
                    "actionSource": "WEB",
                    "statustimestamp": "1698251501",
                    "fanspeed": "fanspeed",
                    "mode": "mode",
                    "swing": " ",
                    "followme": "off",
                    "ontimestamp": "1698239951",
                    "power": "on",
                    "modeTimestamp": "1698179273",
                    "timestamp": "1698240754",
                    "moderules": "default:default:default:default"
                },
                "wifiName": "redacted",
                "userId": "redacted",
                "applianceSubtype": 1,
                "isOnceSyncedState": 1,
                "isFotaRequired": 1,
                "isUpdatingFw": 0,
                "fwInitiatedAt": 0,
                "fpFailureAttempts": 0,
                "fpSuccessAttempts": 0,
                "turboFailureAttempts": 0,
                "turboSuccessAttempts": 0,
                "scheduleDetails": {},
                "isBlocked": 0,
                "blockMessage": "Unblocked",
                "groupId": "-1",
                "deviceSettings": {
                    "isBleAlwaysEnabled": "0"
                },
                "latestBucketError": "0",
                "thermostatDeviceId": "N/A",
                "structureId": "N/A",
                "thermostatHomeAway": {},
                "bleMacAddress": "redacted",
                "isBacktrackEnabled": 1,
                "latEnv": {
                    "temp": 82.0,
                    "humidity": 51.0
                },
                "humCalibrationOffset": "0",
                "tempCalibrationOffset": "0",
                "isHumCalibrationSync": 1,
                "isTempCalibrationSync": 1,
                "myRules": [],
                "myRuleConfiguration": {},
                "deviceFilterDuration": "14",
                "deviceFilterFlag": 1,
                "filterTimestamp": 1698251469,
                "deviceFilterDurationValue": 864,
                "isWifiDisabled": 0,
                "priority": 1
            }
        ],
        "listGroups": [],
        "devicesCount": 1
    }
}
```

When it's turned off, the web UI shows off:

<img width="569" alt="image" src="https://github.com/bodyscape/cielo_home/assets/1387649/242391cb-5ea5-4972-8beb-38e62b5804a7">

... and HA still shows it off:

<img width="609" alt="image" src="https://github.com/bodyscape/cielo_home/assets/1387649/e3f60a04-16e8-42b6-a9f9-1f6e21248081">

Here is the API response:

```{
    "status": 200,
    "message": "SUCCESS",
    "data": {
        "iosVersion": "4.4.0",
        "iosLatestVersion": "4.4.0",
        "iosExpiryTime": 1693508400,
        "androidVersion": "5.4.6",
        "androidLatestVersion": "5.5.4",
        "androidExpiryTime": 1640977200,
        "manufactureDBversion": "1009.28",
        "comfyMinimumLimit": {
            "fahRoomTemp": 0,
            "celRoomTemp": 0,
            "roomHumidity": 3
        },
        "listDevices": [
            {
                "isLocalDbAck": 0,
                "deviceId": "qcYk9g",
                "isFaren": 1,
                "macAddress": "redacted",
                "deviceName": "Garage",
                "fwVersion": "1.0.2,1.0.2",
                "connectionSource": 1,
                "deviceType": "BREEZ-LITE",
                "deviceTypeVersion": "BL02",
                "suggestedRemotes": [
                    {
                        "applianceId": "2120",
                        "protocolId": 402,
                        "isFaren": 1,
                        "priority": 6
                    },
                    {
                        "applianceId": "2710",
                        "protocolId": 770,
                        "isFaren": 1,
                        "priority": 6
                    }
                ],
                "broadcastName": "Cielo_BL02_F9B78C",
                "deviceTimeZone": "-04:00",
                "deviceTimeZoneName": "America/New_York",
                "applianceId": 2120,
                "applianceType": "AC",
                "isEnergyDevice": 0,
                "createdAt": 1698179297,
                "retainCreatedAt": 1698179297,
                "deviceStatus": 1,
                "latestAction": {
                    "uirules": "default:default:default:default",
                    "deviceStatus": "off",
                    "temp": "78",
                    "actionSource": "WEB",
                    "statustimestamp": "1698251501",
                    "fanspeed": "fanspeed",
                    "mode": "mode",
                    "swing": " ",
                    "followme": "off",
                    "ontimestamp": "1698254017",
                    "power": "off",
                    "modeTimestamp": "1698179273",
                    "timestamp": "1698254017",
                    "moderules": "default:default:default:default"
                },
                "wifiName": "redacted",
                "userId": "redacted",
                "applianceSubtype": 1,
                "isOnceSyncedState": 1,
                "isFotaRequired": 1,
                "isUpdatingFw": 0,
                "fwInitiatedAt": 0,
                "fpFailureAttempts": 0,
                "fpSuccessAttempts": 0,
                "turboFailureAttempts": 0,
                "turboSuccessAttempts": 0,
                "scheduleDetails": {},
                "isBlocked": 0,
                "blockMessage": "Unblocked",
                "groupId": "-1",
                "deviceSettings": {
                    "isBleAlwaysEnabled": "0"
                },
                "latestBucketError": "0",
                "thermostatDeviceId": "N/A",
                "structureId": "N/A",
                "thermostatHomeAway": {},
                "bleMacAddress": "redacted",
                "isBacktrackEnabled": 1,
                "latEnv": {
                    "temp": 82.0,
                    "humidity": 52.0
                },
                "humCalibrationOffset": "0",
                "tempCalibrationOffset": "0",
                "isHumCalibrationSync": 1,
                "isTempCalibrationSync": 1,
                "myRules": [],
                "myRuleConfiguration": {},
                "deviceFilterDuration": "15",
                "deviceFilterFlag": 1,
                "filterTimestamp": 1698254017,
                "deviceFilterDurationValue": 906,
                "isWifiDisabled": 0,
                "priority": 1
            }
        ],
        "listGroups": [],
        "devicesCount": 1
    }
}
```

Also, there is no option in HA for the mode:

<img width="174" alt="image" src="https://github.com/bodyscape/cielo_home/assets/1387649/fd598459-c662-4d37-a393-c3fafcd4aeba">

**Comment by bodyscape** [comment]
"latestAction": {
                    "uirules": "default:default:default:default",
                    "**deviceStatus": "off",**
                    "temp": "78",
                    "actionSource": "WEB",
                    "statustimestamp": "1698251501",
                    "fanspeed": "fanspeed",
                    "mode": "mode",
                    "swing": " ",
                    "followme": "off",
                    "ontimestamp": "1698254017",
                    **"power": "off",**
                    "modeTimestamp": "1698179273",
                    "timestamp": "1698254017",
                    "moderules": "default:default:default:default"
                },

the api return is off!

**Comment by bodyscape** [comment]
"latestAction": {
                    "uirules": "default:default:default:default",
                    **"deviceStatus": "off",**
                    "temp": "78",
                    "actionSource": "WEB",
                    "statustimestamp": "1698251501",
                    "fanspeed": "fanspeed",
                    "mode": "mode",
                    "swing": " ",
                    "followme": "off",
                    "ontimestamp": "1698239951",
                    "power": "on",
                    "modeTimestamp": "1698179273",
                    "timestamp": "1698240754",
                    "moderules": "default:default:default:default"
                }

the devicestatus is off, i really weird!

**Comment by jgennari** [comment]
Yea, it's strange. I think they're utilizing the `"power": "on"` field for driving the UI.

**Comment by bodyscape** [comment]
you can check the json msg in the websocket connection what you have for device_status

![image](https://github.com/bodyscape/cielo_home/assets/30115568/caf48f86-036b-4f45-8057-c290d1b6d253)

**Comment by jgennari** [comment]
I tried multiple actions but none of the WS payloads contain a `device_status` field:

<img width="1461" alt="image" src="https://github.com/bodyscape/cielo_home/assets/1387649/340264dc-8130-479c-8251-8771fdea469d">

**Comment by bodyscape** [comment]
In js object actions what do you have? I can't see all properties on your screenshot.

**Comment by jgennari** [comment]
Sorry, here ya go:

<img width="579" alt="image" src="https://github.com/bodyscape/cielo_home/assets/1387649/7b465da8-1ff8-414a-8d43-890f667db039">

**Comment by bodyscape** [comment]
Hmmm i have really no idea if you have this behaviour because of the lite version or your appliance model.

**Comment by jgennari** [comment]
Strange! Hopefully more Lite's pop up and others can comment. I feel like the appliance is pretty standard (at least here in the US).

Regardless, thanks for checking!

**Comment by bodyscape** [comment]
Well maybe i could remove the connection state when it's the lite device. It's just weird nobody seem to have also this issue.

**Comment by bodyscape** [comment]
@jgennari Do you want to send me your setup config (token wetc...) to bodyscape@protonmail.com? I think i found something and i want to test it with your device.

**Comment by jgennari** [comment]
@bodyscape just sent it!

**Comment by bodyscape** [comment]
> @bodyscape just sent it!

I'm out of town, i'll check it probably Wednesday. Happy new year!

**Comment by bodyscape** [comment]
mine look like this :

{
                "protocolId": 3,
                "applianceId": 1674,
                "manufacturerId": 202,
                "name": "Cielo",
                "modelNumber": "Model 11 (Celsius)",
                "isFaren": 0,
                "temp": "17:30",
                "tempIncrement": 1,
                "mode": "cool:dry:fan:auto:heat",
                "isMultiModeTempRange": 0,
                "modesTemp": [],
                "fan": "auto:low:medium:high",
                "swing": "auto/stop:adjust",
                "showSwingTray": 1,
                "isScreenless": 0,
                "is485IR": 0,
                "modeRules": {
                    "cool": {
                        "mode_rules": "default:default:default",
                        "ui_rules": "default:default:default"
                    },
                    "dry": {
                        "mode_rules": "default:default:default",
                        "ui_rules": "default:default:vanish"
                    },
                    "fan": {
                        "mode_rules": "default:default:default",
                        "ui_rules": "vanish:default:default"
                    },
                    "auto": {
                        "mode_rules": "default:default:default",
                        "ui_rules": "default:default:vanish"
                    },
                    "heat": {
                        "mode_rules": "default:default:default",
                        "ui_rules": "default:default:default"
                    },
                    "freezepoint": {
                        "mode_rules": "default:default:default",
                        "ui_rules": "default:default:default"
                    },
                    "turbo_on/off": {
                        "mode_rules": "default:default:default",
                        "ui_rules": "default:default:default",
                        "mode": "on/off"
                    }
                },
                "isDisplayLight": 1,
                "isLightBasestring": 1,
                "isSwingBasestring": 1,
                "isTurboBasestring": 1,
                "displayLight": "on/off",
                "oppositeUnitId": 1675,
                "isTurboDisplay": 1,
                "turboConfig": "default,default:Turbo:heat,cool,auto:temp,swing,light,followme:0:1",
                "turbo": "on/off",
                "isFreezepointDisplay": 1,
                "freezepointConfig": "heat,FP,10,FP:FP:heat:swing,light,followme:1",
                "freezepoint": "freezepoint",
                "isFollowmeDisplay": 1,
                "followmeConfig": "default,default:Follow Me:heat,cool,auto,freezepoint:temp,fanspeed,swing,light,turbo:0",
                "followme": "on:off",
                "serviceFunctions": [
                    {
                        "name": "E1",
                        "description": "Filter Replacement Reminder",
                        "unit": "n/a",
                        "control_type": "toggle",
                        "values": [
                            "off",
                            "on"
                        ]
                    },
                    {
                        "name": "E5",
                        "description": "Heat/Cool priority for Multi-zone systems",
                        "unit": "n/a",
                        "control_type": "list",
                        "values": [
                            "cooling",
                            "heating"
                        ]
                    },
                    {
                        "name": "F1",
                        "description": "Auto Start",
                        "unit": "n/a",
                        "control_type": "toggle",
                        "values": [
                            "off",
                            "on"
                        ]
                    },
                    {
                        "name": "F2",
                        "description": "Heating Temperature Compensation",
                        "unit": "degree",
                        "control_type": "numericrange",
                        "values": [
                            "-6",
                            "-5",
                            "-4",
                            "-3",
                            "-2",
                            "-1",
                            "0",
                            "1",
                            "2",
                            "3",
                            "4",
                            "5",
                            "6"
                        ]
                    },
                    {
                        "name": "F4",
                        "description": "Indoor Fan Motor Speed",
                        "unit": "n/a",
                        "control_type": "list",
                        "values": [
                            "idle",
                            "slow",
                            "on",
                            "intermittent"
                        ]
                    },
                    {
                        "name": "F5",
                        "description": "Louver Angle Memory",
                        "unit": "n/a",
                        "control_type": "list",
                        "values": [
                            "disabled",
                            "enabled",
                            "poweroffonly"
                        ]
                    },
                    {
                        "name": "F6",
                        "description": "Combination of Heat/Cool settings enabled",
                        "unit": "n/a",
                        "control_type": "list",
                        "values": [
                            "both",
                            "heat",
                            "cool"
                        ]
                    },
                    {
                        "name": "F7",
                        "description": "Cooling Temperature Compensation",
                        "unit": "degree",
                        "control_type": "number",
                        "values": [
                            "-2",
                            "-1",
                            "0",
                            "1",
                            "2"
                        ]
                    }
                ],
                "serviceFunctionsDefault": {
                    "E5": "cooling",
                    "F6": "both",
                    "F7": "0",
                    "F1": "off",
                    "E1": "off",
                    "F2": "0",
                    "F4": "idle",
                    "F5": "disabled"
                },
                "isServFuncDisplay": 1,
                "isEvenTemp": 1
            }

**Comment by bodyscape** [comment]
try version 1.6.6-Pre6. Keep you can change the temperature with the default climate, ha don't support that mode. I add two button in the detail of the device!

**Comment by jgennari** [comment]
It worked! I see the up and down temperature controls in the details and can confirm it works now. Thanks for working on it, I was in my office all day hearing you test against it. Thanks for getting the Lite working!

**Comment by bodyscape** [comment]
No problem, but the problem was not the Cielo Lite but a compatibility with my integration and your HVAC model. ;)
