### ISSUE TITLE
How to enable Cielo Follow Me mode?

### ISSUE THREAD

**Issue by miles267** [bodyscape/cielo_home#37]
Hi - how do you call/enable the Cielo Breez Max Follow Me mode within HA? Currently I can do it from within the Cielo iOS app (it toggles on or off) along with the LED mode on/off. Thanks.

**Comment by bodyscape** [comment]
you can't, the integration dont support that.

**Comment by miles267** [comment]
> you can't, the integration dont support that.

Thanks @bodyscape. Is this a feature that could be potentially added? Considering the Cielo app allows for the toggling of these options, each being either enable or disabled, could that in any way be called via the API?

**Comment by bodyscape** [comment]
probably, but i'm alone to do this integration and i don't have a Cielo Breez Max.

**Comment by mikeyoon** [comment]
I have a Breez Max and might be able to make a PR if you can give me the rough outline of what to change. As far as I can tell, it's just another action with the name "followme" with values on/off.

**Comment by bodyscape** [comment]
That's not the only change they made, all communication messages are changed. If the only change was what you suggest,i already made it.

**Comment by miles267** [comment]
> I have a Breez Max and might be able to make a PR if you can give me the rough outline of what to change. As far as I can tell, it's just another action with the name "followme" with values on/off.

Thanks @mikeyoon this would be awesome if you wouldn’t mind taking this feature on.

**Comment by mikeyoon** [comment]
I've submitted PR https://github.com/bodyscape/cielo_home/pull/38 that might need some minor cleanups. It works fine for my purposes, allowing me to turn on follow me automatically whenever my AC turns on.

**Comment by miles267** [comment]
@bodyscape is this something that can be released?  Thanks.

**Comment by bodyscape** [comment]
@miles267 Did you fix the PR. I ask for a couple change!

**Comment by miles267** [comment]
Apologies @bodyscape for any confusion.  Unfortunately I am not a technical developer and wouldn't be able to be of much help.  But I think maybe @mikeyoon can?

**Comment by mikeyoon** [comment]
I haven't had a chance to work on it yet. Hopefully I'll get to it this week.

**Comment by bodyscape** [comment]
The code is merge. Try the version 1.6.4

**Comment by miles267** [comment]
Thanks!  Just updated to 1.6.4.  Is there any doc available on how to enable or toggle the FOLLOW ME feature within HA?

**Comment by miles267** [comment]
Thanks @bodyscape.  I've re-added that card to dashboard and it now appears.  I was actually incorrectly looking at this consolidated card as shown here.
![collapsed_card](https://github.com/bodyscape/cielo_home/assets/55923532/84cdd527-7240-4180-b9bc-86be1036fc1d)
