### ISSUE TITLE
Freezing Point no longer working

### ISSUE THREAD

**Issue by the-gray-ghost** [bodyscape/cielo_home#39]
For some reason the Freezing Point setting is no longer working.  When I toggle it on, it turns itself back off again after a few seconds.  I have only one unit turned on, in heat mode, when I toggle the switch.  I have also tried turning it on from OFF, the unit turns on, but only to heat mode, the toggle resets this way as well.

Also, Freezing Point is the only entity that is not passing through the HomeKit Bridge, even though it is enabled (not excluded).

**Comment by the-gray-ghost** [comment]
With more testing, I can disable Freeze Protection with the Home Assistant toggle (when I enable FP using the Mr Cool app).  I just cannot enable it with HA.

Also, the entities finally showed up today in HomeKit, not sure why it took so long.

**Comment by bodyscape** [comment]
@the-gray-ghost i can close this issue? i'm not sur to understand the problem.
