### ISSUE TITLE
Sync AC State

### ISSUE THREAD

**Issue by montesn** [bodyscape/cielo_home#4]
The integration has been working great, this is a feature request. I'm having an issue related to the physical Cielo device itself where occasionally the AC doesn't see the IR signal and the app and AC get out of sync. I've tried manually setting the state in Home Assistant with a python script, but it seems that if the Cielo app still thinks it's on, it won't respond accordingly. The app does have an option to sync the AC state as shown in the screenshot. Is there any way to integrate this functionally into your integration to call it from HA?
![Screenshot_20230316-071215](https://user-images.githubusercontent.com/32144370/225614274-381b0389-d63c-4340-a3c3-d910769cdffb.png)

**Comment by montesn** [comment]
I wasn't aware of that website, but good to know for the future. It appears the option exists there. If you hit the "Settings" cog in the upper right corner, you get this dialog with the "Sync" option as a tab on the left:
![image](https://user-images.githubusercontent.com/32144370/225663515-c7a8d8f8-2179-4d4d-ba5b-992d2866dc5d.png)

Sync gives you the option to tell it that the system is actually off, or that the system is actually on and what mode and temperature. 

I'd love this functionality so that I can set up an automation in Home Assistant to monitor either the Cielo thermostat temperature (or another sensor in my garage) and when the temperature gets several degrees out of range, indicating that the system is not on or off as the Cielo thinks, Home Assistant can trigger a sync to tell Cielo the actual state of the system. From there, I can either have HA manually change the state of the AC or test to see if Cielo figures out it's still out of range and turns on by itself.

**Comment by bodyscape** [comment]
Well i understand if i have others requests i'll do it. ;) You are also welcome to do it and make a pull request to add it to the repo.

You have really a weird behavior.

**Comment by montesn** [comment]
I'll wait to see if it gets added. This is not an ideal scenario, this is just meant as a workaround for the fact that the Cielo Breeze seems to miss an IR command on occasion and gets out of sync with the AC.

**Comment by bodyscape** [comment]
Just to remind you i'm the one who make the integration and for now I'm the only one work on it. ;) So i will close this issues who is not a issue. Maybe i'll do it when i add a other features.

**Comment by bodyscape** [comment]
@montesn the release 1.4.1 support the Sync AC State. Have fun!

**Comment by montesn** [comment]
> @montesn the release 1.4.1 support the Sync AC State. Have fun!

Thanks for your hard work!
