### ISSUE TITLE
Failed Authentication

### ISSUE THREAD

**Issue by yodashut** [bodyscape/cielo_home#41]
I noticed my integration stopped working this morning (couldn't see devices in the integration any more).  I deleted the integration and removed it from HACS, rebooted, re-installed in HACS, rebooted, followed the instructions to get the auth/refresh/user/session ids, closed chrome, re-opned chrome and tried to add the integration again in HA with the data pasted from note pad.  Tried several times and always get a failed authorization response.

**Comment by vitalmem81** [comment]
Oh no, I also just lost communication (says "Unavailable"). We just lost power for a few hours and thought that was it, but I guess not. My phone app still works fine, so it shouldn't be a Cielo server issue. I don't know where the authentication error you are seeing shows up, maybe I can check mine also, if you tell me where to look.

**Comment by yodashut** [comment]
When mine went unavailable, I deleted the integration and started over with the integration freshly installed.  First step in adding the integration is to set up authentication...that is where it fails.

**Comment by fenixstarlord** [comment]
I'm in the same boat as @yodashut 

I've deleted and re-added the integration, but it fails.

**Comment by hambleto** [comment]
I am seeing the same thing. I had thought it might be related to an os update so I rolled the core back to 2023.12.2, removed integration, and reinstalled and still get the same issue.

**Comment by abanach** [comment]
same comment as [vitalmem81](https://github.com/vitalmem81). lost power, uninstalled, rebooted, reinstalled, rebooted, got tokens, etc. no joy.

**Comment by bsell93** [comment]
@bodyscape having the same issue. Not sure if cielo was doing this before but I noticed they have a `X-Api-Key` request header. Perhaps that's another auth config value we need to save that they recently added?

**Comment by ahuffman** [comment]
All my Cielo devices I just noticed today are now saying unavailable as well.  I have not gone down the path of uninstalling and re-configuring a new auth token yet..., but based on what I'm seeing here I'm going to wait until this gets debugged a bit further.  Sounds like something changed again in the auth mechanism with Cielo.  I don't know why they won't just publish an API for us to use :(.

**Comment by bsell93** [comment]
Okay, so I'm able to call the `https://api.smartcielo.com/web/devices?limit=420` url directly in postman with the `Authorization` and `x-api-key` header values set and get a successful response from Cielo's api. So I strongly suspect it's something to do with the integration itself.

**Comment by bodyscape** [comment]
They move the api key in the js file so the integration don't find it anymore.. i'll fix it.

**Comment by bodyscape** [comment]
not exactly, it's seem now they have 2 different X-Api-Key before it was the same key 

for login request : X-Api-Key:
XiZ0PkwbNlQmu3Zrt7XV3EHBj1b1bHU9k02MSJW2

for devices request 
X-Api-Key:
7EORvce3Cm80izjdODnGSafHYggxGSKw7U23BVzi

weird!

**Comment by bsell93** [comment]
Are you using a tool to be able to read the main.js file? Mine looks heavily minified and with hexcodes for variables and such.

**Comment by bodyscape** [comment]
try the version 1.6.5 you should be ok!

**Comment by yodashut** [comment]
@bodyscape YOU FIXED IT!  Than you!

**Comment by bsell93** [comment]
Thanks again @bodyscape 😁👍🏻
