### ISSUE TITLE
Followed Instructions, no longer appears to authenticate

### ISSUE THREAD

**Issue by JCoreMS** [bodyscape/cielo_home#46]
Not sure what I'm doing wrong but after a few attempts with in-private and/or shutting all the browsers down, can't seem to get it to authenticate.  Has this been attempted by others recently?  Could Cielo have changed something?

**Comment by Z0y6h0kS9X** [comment]
I just attempted it after upgrading to 1.6.8 and having it stop working.  Tried downgrading back to 1.6.6 and still get the same - could be an issue with cielo's authentication server.  I noticed when I tried to login via the web page, I had to try multiple times as it said 'forbidden' initially.  Could be that they enabled bot protection like [myq did](https://community.home-assistant.io/t/the-current-state-of-myq-from-the-codeowner/630623) recently - but that is baseless speculation.

**Comment by imCharlieB** [comment]
Same with mine my old pi crashed rebuilt it all today and now Cielo wont sign in.

**Comment by bodyscape** [comment]
you try to take a new token from the website right?

![image](https://github.com/bodyscape/cielo_home/assets/30115568/3e6e8ad2-9a44-4c0f-927d-7e5a053ca5a2)

You must **not** sign out on the website after that, because it will expire the token right now

**Comment by imCharlieB** [comment]
Correct same way i did it the first time i set it up.. tried it a few times to make sure i was doing it right

**Comment by vitalmem81** [comment]
My interface went "unavailable" about an hour ago. It had just worked this morning. I had not done anything to the HA or the integration. I rebooted HA, and it still does not connect. Thanks for looking into any new issues, I'm hoping this interface will become reliable.

**Comment by bodyscape** [comment]
fix in version 1.6.9

**Comment by imCharlieB** [comment]
Thanks that worked
