### ISSUE TITLE
Question on Cielo device temp/humidity polling

### ISSUE THREAD

**Issue by ahuffman** [bodyscape/cielo_home#47]
Hi @bodyscape , was curious if you know how often the local data from the Cielo devices propagate into home assistant?  Been having a problem with my devices not being completely in sync with the actual temp displayed on them in home assistant.  

I use the temp to trigger automation to adjust different heating areas in my house and been noticing the automation isn't being triggered because the home assistant value is above the trigger when in reality the device has a temp below the trigger.

Not sure if this is a device issue (firmware) or if it's something with the integration that needs to poll the cloud more frequently.

**Comment by bodyscape** [comment]
It's live sync, about 1 or 2 second delay.

**Comment by bodyscape** [comment]
But keep in mind when the temp change on your Cielo device it's the Cielo server send a update. I must wait for it.

**Comment by ahuffman** [comment]
Ok thanks for confirming, and I figured as much.  Not sure why some of my Cielo devices don't update the cloud service as expected.  

Anyways thanks for the reply, and as always appreciate your work maintaining this project!
