### ISSUE TITLE
I have lost half of my entities

### ISSUE THREAD

**Issue by TheHuskyCrobats** [bodyscape/cielo_home#48]
Today I have lost half of my entities, from 3 rooms with same model Cielo Breez Eco and same AC Type, suddenly I can control only one, from living through climate.living entity.
The other 2 does not have this control, it dissapeared.

I have deleted the integration and added again, same issue.

I am new to HA, so I really dont know where is the issue and how to solve it.

![image](https://github.com/bodyscape/cielo_home/assets/149390002/cc9e82aa-d824-4b5a-9ed0-5dfc25b73843)
![image](https://github.com/bodyscape/cielo_home/assets/149390002/cd1e51ff-0f72-4e16-893b-840857b650fb)
![image](https://github.com/bodyscape/cielo_home/assets/149390002/185eee52-5fae-475a-9917-5fb166cda25e)
![image](https://github.com/bodyscape/cielo_home/assets/149390002/d9e27fd4-5f91-4fcd-9fb8-9495492b6599)

**Comment by TheHuskyCrobats** [comment]
I tried again today to reinstall it from scratch.
So I removed the integration, restarted HA, redownloaded the integration and restarted HA, add all credentials and ... same issue.
I was looking at documentation but nothing is mentioned there about different entities for same devices.

So below is the screenshot of the devices/entities as it should be:
![image](https://github.com/bodyscape/cielo_home/assets/149390002/58e75df9-f0e5-4808-a817-3edcf997906f)

And this is one of my device/entity whic still has some control (but not all)
![image](https://github.com/bodyscape/cielo_home/assets/149390002/a06758ce-f8e7-49d4-b699-b3601fa74c7f)

And this is one of the other 2 device which have only one control .... Power ...
![image](https://github.com/bodyscape/cielo_home/assets/149390002/c4e0f3ba-3109-4d8c-9f02-6264ecd94bb6)

No ideea what is happening ...

**Comment by bodyscape** [comment]
good question, if you send me your login and password i can check on it : bodyscape@protonmail.com

**Comment by TheHuskyCrobats** [comment]
Hi,

User: ***@***.***
Pass: Dg6j7CTi4SQ-T3l

Let me know how it looks for you.

Best regards,
Cristian.


------------------------------
Rule no. 32: Enjoy little things...


În mar., 23 ian. 2024 la 14:28, bodyscape ***@***.***> a
scris:

**Comment by bodyscape** [comment]
It's your AC_farmacie there are not appliance link to it and it crash. try the version 1.7.0 you will be ok.

**Comment by TheHuskyCrobats** [comment]
I really did not think that if one device is not linked it can create so many issues with the others.
I just manually configured an AC unit for that device and all is ok now.

Thank you for your help.
