### ISSUE TITLE
Unable to set 'Heat' below 18 degrees....

### ISSUE THREAD

**Issue by andypnz** [bodyscape/cielo_home#50]
Hi. I have a Cielo Breeze connected to my heat pump. Works great. Using the Cielo app I can set the temperature for heating over a range of 10 - 30 degrees Celsius. It is connected to Google Home, and I can set the temperature (for heating) to anywhere between 10 - 32 degrees Celsius.

Using this great HACS addition with HA, the lowest temperature I can set for heating is 18 degrees Celcius. 

Is it possible to change this minimum to be 16 degrees (this is the temperature I set the heat pump to overnight)? Currently I am needing to use the Cielo app or Google Home to do this - and I would prefer to use HA....

Thanks!

**Comment by bodyscape** [comment]
it's not a default value, i receive this configuration from Cielo server

**Comment by andypnz** [comment]
Is it possible for this to be modified? Both my Cielo app and Google Home let me go down as low as 10 degrees on heat.

**Comment by bodyscape** [comment]
go there : https://home.cielowigle.com/

and send me this 

![image](https://github.com/bodyscape/cielo_home/assets/30115568/f03c64de-d295-49a2-9af7-d0082c0d8d79)

**Comment by andypnz** [comment]
Thanks.... please see below......

`{
    "status": 200,
    "message": "SUCCESS",
    "data": {
        "listAppliances": [
            {
                "protocolId": 44,
                "applianceId": 1707,
                "manufacturerId": 202,
                "name": "Cielo",
                "modelNumber": "Model 33 (Celsius)",
                "isFaren": 0,
                "temp": "18:32",
                "tempIncrement": 1,
                "mode": "cool:dry:fan:auto:heat",
                "isMultiModeTempRange": 1,
                "modesTemp": [
                    {
                        "mode": "cool",
                        "temp": "18:32"
                    },
                    {
                        "mode": "heat",
                        "temp": "10:30"
                    },
                    {
                        "mode": "auto",
                        "temp": "18:30"
                    },
                    {
                        "mode": "dry",
                        "temp": "18:32"
                    },
                    {
                        "mode": "fan",
                        "temp": "18:32"
                    }
                ],
                "fan": "auto:low:medium:high",
                "swing": "auto:pos1",
                "showSwingTray": 0,
                "isScreenless": 0,
                "is485IR": 0,
                "modeRules": {
                    "cool": {
                        "mode_rules": "default:default:default",
                        "ui_rules": "default:default:default"
                    },
                    "dry": {
                        "mode_rules": "32:default:auto",
                        "ui_rules": "vanish:default:vanish"
                    },
                    "fan": {
                        "mode_rules": "25:default:default",
                        "ui_rules": "vanish:default:default"
                    },
                    "auto": {
                        "mode_rules": "default:default:default",
                        "ui_rules": "default:default:default"
                    },
                    "heat": {
                        "mode_rules": "default:default:default",
                        "ui_rules": "default:default:default"
                    },
                    "turbo_off": {
                        "mode_rules": "default:default:default",
                        "ui_rules": "default:default:default",
                        "mode": "off"
                    },
                    "turbo_on": {
                        "mode_rules": "default:default:default",
                        "ui_rules": "vanish:default:vanish",
                        "mode": "on"
                    }
                },
                "isDisplayLight": 0,
                "isLightBasestring": 0,
                "isSwingBasestring": 0,
                "isTurboBasestring": 0,
                "displayLight": "on:off",
                "oppositeUnitId": 1710,
                "isTurboDisplay": 1,
                "turboConfig": "default,default:Power:cool,heat,fan,dry,auto:swing,mode:20:1",
                "turbo": "off:on",
                "isFreezepointDisplay": 0,
                "freezepointConfig": "",
                "freezepoint": "freezepoint",
                "isFollowmeDisplay": 0,
                "followmeConfig": "",
                "followme": "",
                "serviceFunctions": null,
                "serviceFunctionsDefault": null,
                "isServFuncDisplay": 0,
                "isEvenTemp": 1
            }
        ]
    }
}`

**Comment by bodyscape** [comment]
i found why at least. This integration don't support isMultiModeTempRange, that's the reason why. i'll check on it. But i don't know when.


![image](https://github.com/bodyscape/cielo_home/assets/30115568/7bb140cf-4281-4f44-aeb6-52f12c234d8b)

**Comment by bodyscape** [comment]
try the Version 1.7.1-Pre1

**Comment by andypnz** [comment]
Thank you... could you point me at a quick guide as to how I update to 1.7.1-Pre1? Can I do this within HACS? Or some other method? Thanks!

**Comment by bodyscape** [comment]
![image](https://github.com/bodyscape/cielo_home/assets/30115568/3c6a9410-0cb3-4516-9b72-631eecba58cb)

i will see the release

**Comment by andypnz** [comment]
Not sure how to bring up that menu.... I guess it is from the Cielo update information menu? When I click update information, nothing happens...
![image](https://github.com/bodyscape/cielo_home/assets/11356342/d20fa3d3-0a57-46b5-a01c-4d8cd49929e3)

**Comment by bodyscape** [comment]
![image](https://github.com/bodyscape/cielo_home/assets/30115568/a5c1733a-e54e-46e9-918d-0f42e515ead3)

![image](https://github.com/bodyscape/cielo_home/assets/30115568/31abfc59-6871-4e03-87d6-cf94ae3e1640)

**Comment by andypnz** [comment]
Working perfectly! Thank you very much for sorting that :-)
