### ISSUE TITLE
'Set target temperature' service call HVAC Mode parameter not working

### ISSUE THREAD

**Issue by ki4hrg** [bodyscape/cielo_home#51]
**What's expected:** When calling the `Set target temperature` service with both the `Temperature` and `HVAC mode` parameters defined on a device that is currently powered off, the device should power on and the mode and target temperature set on the device.

**What's happening:** When calling the service with both parameters defined, the device does not power on and the parameters are not set. If the device is already powered on the temperature is set, and if the mode is set using the `Set HVAC mode` service the device powers on if turned off when the service is called.

Note that if _only_ the HVAC mode parameter is defined, the trace reflects an error that the temperature parameter is required.

**Installation details:**
Home Assistant:
Core 2024.1.5
Supervisor 2023.12.1
Operating System 11.4

Cielo Integration v1.7.0

Device Model BREEZ-PLUS (BP01)
Firmware: 1.1.1,2.4.1

**Comment by bodyscape** [comment]
@ki4hrg try the version [1.7.1](https://github.com/bodyscape/cielo_home/releases/tag/1.7.1)

**Comment by ki4hrg** [comment]
That seems to have resolved it. Thanks!
