### ISSUE TITLE
loss of connectivity after updating to 1.7.1

### ISSUE THREAD

**Issue by abanach** [bodyscape/cielo_home#52]
Updated to 1.7.1 just a little while ago and now cannot connect to any my minisplit units

**Comment by cwtufts** [comment]
Same here. Updated it and now nothing. Will not let me sign back in using the tokens. Says invalid authenication.

**Comment by bodyscape** [comment]
@abanach @cwtufts install the version 1.7.2. I fix the change from the Cielo server!

**Comment by cwtufts** [comment]
I keep getting an unexpected error. I have updated and still not working do I need to remove integration and reinstall?

**Comment by abanach** [comment]
installed 1.7.2 manually, restarted HA and all is good

**Comment by bodyscape** [comment]
> I keep getting an unexpected error. I have updated and still not working do I need to remove integration and reinstall? 

Yes reinstall from scratch

**Comment by cwtufts** [comment]
> > I keep getting an unexpected error. I have updated and still not working do I need to remove integration and reinstall? 
> 
> Yes reinstall from scratch 

I have removed, then restarted, and loaded it manually and I am still getting unexpected error. What else can I do?

**Comment by bodyscape** [comment]
Do you have a error log in HA?

**Comment by cwtufts** [comment]
> Do you have a error log in HA?
2024-01-30 19:38:39.999 ERROR (MainThread) [custom_components.cielo_home.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/cielo_home/config_flow.py", line 68, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/cielo_home/config_flow.py", line 37, in validate_input
    if not await api.try_async_refresh_token(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/cielo_home/cielohome.py", line 167, in try_async_refresh_token
    config_data = self._entry.data.copy()
                  ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by bodyscape** [comment]
try the version 1.7.3
