### ISSUE TITLE
Cielo 1.7.3 HA integration - Failed to Setup

### ISSUE THREAD

**Issue by miles267** [bodyscape/cielo_home#53]
Have been running the integration smoothly without intervention. However today HA is reporting the Cielo integration 1.7.3 has failed to setup. Anyone else experiencing this yet? HA 2014.1.6.

**Comment by bodyscape** [comment]
do you have any error log?

**Comment by miles267** [comment]
@bodyscape actually I don't -- in fact i've never had to capture one before (the issues usually get addressed with new app updates before I encounter them).  I'm glad to capture and provide.  Can you please provide quickest method of doing this?  Thanks.

**Comment by bodyscape** [comment]
Google how to check logs in HA, there are a lot of information and tutorial.

**Comment by miles267** [comment]
@bodyscape attached as requested.
[home-assistant_cielo_home_2024-02-03T17-48-17.213Z.log](https://github.com/bodyscape/cielo_home/files/14152521/home-assistant_cielo_home_2024-02-03T17-48-17.213Z.log)

**Comment by miles267** [comment]
@bodyscape added log

**Comment by bodyscape** [comment]
did you try to uinstall it and reinstall?

**Comment by miles267** [comment]
> did you try to uinstall it and reinstall?

Hi @bodyscape yes, I just successfully uninstalled and reinstalled and it seems functionality has been restored.  I've never had to do this before so I'm unsure what prompted this.  Thank you.
