### ISSUE TITLE
Cielo Home reads current unit but can not write a change to unit

### ISSUE THREAD

**Issue by vitalmem81** [bodyscape/cielo_home#59]
If I change the unit temperature via the Cielo app, the unit changes, and it is reflected in the HACS Cielo Home HA card. However, if I change the temperature on the HA card, it is not changed at the unit. There is no error, and the card remains on the changed temperature, but the target is still the previous one set by the Cielo app. This worked fine until today.

**Comment by asrrin29** [comment]
Can confirm I am having the same issue.  I did update the Home Assistant Core today to 2024.5.2 from the latest version prior, and I have restarted the entire server several times but it's not fixing the issue.

**Comment by jduff001** [comment]
Same issue here.. in the past I just reloaded the integration.. but now it just reading the entities.  I can not change any of the settings.
core 2024.5.2
supervisor 2024.05.1
operating system 12.3
frontend 20240501.1

**Comment by kamalaboulhosn** [comment]
Also seeing this issue starting today. I enabled debug logging and it looks like Cielo is returning errors:

```
2024-05-10 11:10:13.811 DEBUG (MainThread) [custom_components.cielo_home.cielohome] Receive Json : {"message": "Internal server error", "connectionId": "-------", "requestId": "-------"}
```

I didn't do any updates today. Currently running:

* Core 2024.4.1
* Frontend 20240404.1

**Comment by r14n** [comment]
Same issue here

**Comment by dbaron92** [comment]
Same here. I upgraded my HA to 2024.5.2 in few days and noticed the issue today. I rollback to 2024.4.4 and same issue so I assumed that its not related to HA's OS upgrade. The log stated
`Entity None (<class 'custom_components.cielo_home.climate.CieloHomeThermostat'>) implements HVACMode(s): off, cool, dry, fan_only, auto, heat and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/bodyscape/cielo_home/issues`

**Comment by bodyscape** [comment]
Probably a change on the cielo server. I'll check on it

**Comment by VeitX** [comment]
Same over here without any update. Tried to redo the connection. Same thing. Can read but not write. Great job with your integration btw!

**Comment by jdbarnes63** [comment]
Same here, noticed that it started today when automation ran and nothing happened on Cielo side. Had this issue a month ago and it was fixed within a few days.

**Comment by macjustice** [comment]
Same symptoms, reports the state but doesn't actually send the IR commands. Happy to fetch logs or something if that would help.

**Comment by bodyscape** [comment]
Fix on the version 1.7.5, please try it.

**Comment by jdbarnes63** [comment]
Thanks for the quick fix. 1.7.5 works perfectly. No issues, can control from HA or Apple HomeKit integration. All automations running again.

**Comment by kamalaboulhosn** [comment]
All working perfectly again. Thanks for the quick fix and the integration as a whole!

**Comment by asrrin29** [comment]
Can also confirm it's working.  Thanks so much for the quick turnaround!

**Comment by r14n** [comment]
> Fix on the version 1.7.5, please try it.

You da man!

**Comment by vitalmem81** [comment]
Works great, thanks again for your awesome support! Bought some more coffee for you. Cheers.

**Comment by iRonin** [comment]
Was having exactly the same issue. How come the update does not show in HA? I see other HACS ready for update but not this one.

**Comment by asrrin29** [comment]
@iRonin you may need to go into HACS and select "Redownload" from the 3 dots menu of the Cielo Home integration.  I did that and it showed up as available to install/update.

**Comment by iRonin** [comment]
> @iRonin you may need to go into HACS and select "Redownload" from the 3 dots menu of the Cielo Home integration. I did that and it showed up as available to install/update.

Thanks. I just redownloaded and restarted and it's working again.
