### ISSUE TITLE
Not Exposing Climate Entity

### ISSUE THREAD

**Issue by notasz** [bodyscape/cielo_home#60]
I just updated to 1.7.6 after the recent change that Cielo did which caused previous versions to break. Once updated there is no climate entity exposed which breaks thermostat cards, homekit bridge controls, etc. Let me know if there's somewhere I can poke around to try and provide more information. Thanks.

Steps:
1. Updated integration via HACS from 1.7.4 to 1.7.6
2. Restarted HA
3. Removed existing Cielo device
4. Added new Cielo device and successfully connected and checked entity list

![image](https://github.com/bodyscape/cielo_home/assets/1159257/c12f96d9-87d9-4036-957e-fc255b53ff3f)

**Comment by bodyscape** [comment]
update your HA

**Comment by notasz** [comment]
> update your HA

Thank you. Dumb issue on my part, I somehow stuck my container to a static version from 2023 and didn’t realize it wasn’t pulling the latest HA. Sorry for the issue!

**Comment by bodyscape** [comment]
No problem! ;)
