### ISSUE TITLE
Does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method

### ISSUE THREAD

**Issue by TarheelGrad1998** [bodyscape/cielo_home#62]
I think you fixed some version of this error, but I'm getting the below in 2024.6:

Entity None (<class 'custom_components.cielo_home.climate.CieloHomeThermostat'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method.

**Comment by bodyscape** [comment]
@TarheelGrad1998 try version 1.7.7

**Comment by truckerboy** [comment]
Updated via HACS to 1.7.7 and restarted home assistant server. Still getting the following warning:
Entity None (<class 'custom_components.cielo_home.climate.CieloHomeThermostat'>) implements HVACMode(s): off, dry and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/bodyscape/cielo_home/issues

**Comment by TarheelGrad1998** [comment]
Hrm, interesting.  I updated this morning to 1.7.7 and restarted, and did not get the error.  Not sure why my experience differs from @truckerboy
