### ISSUE TITLE
Breeze Max

### ISSUE THREAD

**Issue by mworsnop** [bodyscape/cielo_home#65]
do you think there might ever be a version that controls the **breeze** **max** directly without having to go through the Cielo server?

**Comment by bodyscape** [comment]
no idea, but not on this integration!

**Comment by Willardgmoore** [comment]
I am interested in direct control as well. Cielo recently asked me to beta test a new unit they are sending me. If there is a project that is beginning to work on a direct integration, please point it out to me and I will do some work on it. 

I am hoping that a direct integration could allow me to use the unit as an IR receiver/transmitter as well as the rest of the components. It would be nice to be able to turn the leds off on my mini split unit which the remote has a button for, but the cielo does not have the option for.

**Comment by mworsnop** [comment]
I used a $12 USB stick thats flashed with ESP Home.  I control it with Home Assistant.  I has 12 of them and they have been flawless
If you want the website to order let me know

**Comment by Willardgmoore** [comment]
I am new to home assist and have a home assistant green. 

Do I need the usb stick? Did you follow general instructions for esp home or was there something more specific for cielo? Any links would be helpful. 

Were you able to use more of the hardware like I suspect may be possible? ie: using the IR from the cielo for other devices.

**Comment by mworsnop** [comment]
The USB stick I’m talking about goes into the Mini Split wall units. Is
used if you want to have Home Assistant control your heating and air
conditioning for your Mini Split.

This is not Cielo. I used Cielo But they are 10 times more expensive to do
the same thing.

https://smlight.tech/product/slwf-01/

**Comment by Willardgmoore** [comment]
@mworsnop I appreciate your input. I didn't know about being able to add a device directly to the minisplit. I am particularly interested in the cielo unit specifically as I will be beta testing a new unit they are releasing called the Cielo Breeze Edge Pro. Quoted email for context. 

> I hope this message finds you well.
> 
> On behalf of the entire Cielo team, I’m reaching out personally to thank you for your support to become part of the pre-release program of our latest innovation, the Cielo Breez Edge Pro. We truly appreciate your trust and are thrilled to have you be a part of this exclusive pre-release program.
> 
> We’ve shipped your device, and it should arrive shortly. Below are the tracking details for your reference:
> 
> Redacted 
> 
> As Jason discussed during call, your feedback over the coming weeks will be invaluable in refining the Edge Pro. To make the feedback process seamless, we’d like to schedule follow-up calls with you during this period. We anticipate conducting two follow-ups per week to gather your feedback and address any questions you might have. Please let us know which days and times work best for you, and we’ll coordinate accordingly.
>  
> 
> Once again, thank you for placing your trust in Cielo and helping us take this important step forward. If you have any questions or need assistance, please don’t hesitate to reach out to me directly.

**Comment by bodyscape** [comment]
@Willardgmoore Well if you can add me to their pre-release.. i'll try to integrate it to my project..
