### ISSUE TITLE
Can read devices but not write them - Breeze Max 3x

### ISSUE THREAD

**Issue by tsaubergine** [bodyscape/cielo_home#69]
Hi -

I have followed the configuration instructions carefully and repeated it several times (uninstall/reinstall) to make sure I get the same result. Each time I can see my devices and read the state / temperatures as set directly from the Cielo Home app, but any settings I change from HA don't take effect.

I have attached a debug log of attempting to turn on and off one of my devices (Breeze Max) from this integration.

Thanks for any advice you can provide.
[home-assistant_cielo_home_2024-08-19T01-19-31.792Z.log](https://github.com/user-attachments/files/16654083/home-assistant_cielo_home_2024-08-19T01-19-31.792Z.log)

**Comment by bodyscape** [comment]
This integration was never tested with the Breeze Max device.... So don't officially support it.
