### ISSUE TITLE
Add Integration Configuration page

### ISSUE THREAD

**Issue by X-sam** [bodyscape/cielo_home#73]
Right now, `if your HA or this integration don't run for more than 1 hour you must uninstall it and reinstall it.` It would be nice to add a [options flow](https://developers.home-assistant.io/docs/config_entries_options_flow_handler) so these properties could be reset without a full uninstall/reinstall, and thus preserve historical data

**Comment by bodyscape** [comment]
In fact the 1 hour don't really apply. It was speculation on my part. Each time a reboot does the trick ;)
