### ISSUE TITLE
Temperature Sensor no longer exposed as entity?

### ISSUE THREAD

**Issue by StraightfaceStudios** [bodyscape/cielo_home#76]
“ This entity is no longer being provided by the cielo_home integration. If the entity is no longer in use, delete it in settings.”

**Comment by bodyscape** [comment]
more detail please....

**Comment by marbletravis** [comment]
I had a similar issue after updating today. I was able to fix it by reloading the integration after updating (see screenshot).

![Screenshot_20241226-160024.png](https://github.com/user-attachments/assets/ce977c75-79f5-40e2-b977-83cfca4a1668)

**Comment by StraightfaceStudios** [comment]
Thanks, I went a little more extreme and reinstalled and it worked. It sounded like any changes weren’t deliberate so it must have been a backend breakdown.
