### ISSUE TITLE
AC Sync State

### ISSUE THREAD

**Issue by jbr00me** [bodyscape/cielo_home#77]
Noticed that the AC sync state has been commented out of the code and is no longer usable in HA. Nothing in the commit history shows why it's been disabled. Any plans to reimplement?

**Comment by bodyscape** [comment]
Please be more specific. All state values with HA are async.

**Comment by jbr00me** [comment]
The functionality that allows you to sync the actual state of the hvac unit to the cielo unit. Example: The cielo unit says the hvac unit is powered on but the hvac unit itself it actually off. There used to be an action in HA that would allow you sync them up and that function has been commented out in the code. Hopefully this makes more sense.

**Comment by bodyscape** [comment]
I don't remember to code that or comment that...;) which part of the code?

**Comment by jbr00me** [comment]
Totally understand :).....

File: cielohomedevice.py 
lines 128-151

    #    def sync_ac_state(
    #        self, power: bool, temp: int, mode: str, fan_speed: str, swing: str, preset: str
    #    ) -> None:
    #        """None."""
    #        action = self._get_action()
    #        action = {
    #            "power": "on" if power else "off",
    #            "temp": temp
    #            if power and temp > 0
    #            else self._device["latestAction"]["temp"],
    #            "mode": mode
    #            if power and mode != ""
    #           else self._device["latestAction"]["mode"],
    #            "fanspeed": fan_speed
    #            if power and fan_speed != ""
    #            else self._device["latestAction"]["fanspeed"],
    #           "swing": swing
    #           if power and swing != ""
    #            else self._device["latestAction"]["swing"],
    #            "preset": preset
    #            if power and preset != ""
    #            else self._device["latestAction"]["turbo"],
    #        }
    #        self._send_msg(action, "", "", default_action="syncState")

**Comment by bodyscape** [comment]
Hmmm haha i don't remember. I'll check on that!

**Comment by jbr00me** [comment]
That code may not be the issue but I am no longer able to use the Service "Cielo Home: Sync AC State" like you have in your readme

**Comment by bodyscape** [comment]
test the 1.8.0! ;)

**Comment by jbr00me** [comment]
Sweet! The option is now back! Thanks!
